-- 필요 없는 코드
-- ALTER TABLE "event" ALTER COLUMN "event_type" SET DATA TYPE text;--> statement-breakpoint
-- DROP TYPE "public"."event_type";--> statement-breakpoint
-- CREATE TYPE "public"."event_type" AS ENUM('product_view', 'product_visit', 'profile_view');--> statement-breakpoint
-- ALTER TABLE "event" ALTER COLUMN "event_type" SET DATA TYPE "public"."event_type" USING "event_type"::"public"."event_type";
